; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Font,, Calibri
Gui Add, Text, x32 y40 w91 h23 +0x200 vEscolhaArquivo, Escolha o arquivo
Gui Font
Gui Font,, Calibri
Gui Add, Button, x40 y344 w138 h23 vIniciar, Iniciar
Gui Font
Gui Font,, Calibri
Gui Add, Button, x216 y344 w153 h22 vCancelar, Cancelar
Gui Font
Gui Font, s7 Italic cRed, Calibri
Gui Add, Link, x168 y64 w81 h17, <a href="template\template.xlsx">Template padrão</a>
Gui Font
Gui Font,, Calibri
Gui Add, Progress, x40 y312 w325 h21 -Smooth , 0
Gui Font
Gui Font,, Calibri
Gui Add, Button, x320 y40 w24 h21 vBtnEscolhaArquivo, ...
Gui Font
Gui Font,, Calibri
Gui Add, Edit, x120 y40 w198 h21 vCaminhoArquivo Disabled
Gui Font
Gui Font,, Calibri
Gui Add, Edit, x40 y144 w327 h160 vCorpoEmail,  Digite aqui o corpo do e-mail....
Gui Font
Gui Font,, Calibri
Gui Add, Text, x80 y88 w43 h19 +0x200 vAssunto, Assunto
Gui Font
Gui Font,, Calibri
Gui Add, Edit, x120 y88 w199 h20 vTxtAssunto
Gui Font

Gui Show, w461 h431, Envia E-mails
Return

Button...:
    FileSelectFile, OutputVar , Options, %A_Scriptdir%\template
    GuiControl,, CaminhoArquivo, %OutputVar%
    GuiControlGet, CaminhoArquivo
Return
ButtonIniciar:
    xl := ComObjCreate("Excel.Application")
    xl.Visible := true
    xl.Workbooks.Open(CaminhoArquivo)

    Linhas := xl.ActiveSheet.UsedRange.Rows.Count

    Loop, %Linhas%
    {
        if (A_index == 1)
            Continue

        Nome := xl.ActiveSheet.Range("A"A_index).Value
        Email := xl.ActiveSheet.Range("B"A_index).Value

        GuiControlGet, TxtAssunto
        GuiControlGet, CorpoEmail
        recipient := Email
        emailBody := "Olá papai/mamãe de " Nome ","
        emailBody .= "`n " CorpoEmail

        Outlook := ComObjActive("Outlook.Application")
        email := Outlook.Application.CreateItem(0)

        email.Subject := TxtAssunto
        email.HTMLbody := emailBody
        email.To := recipient

        email.display

        email.send()
    }
    
Return
ButtonCancelar:
    ExitApp
GuiEscape:

GuiClose:
    ExitApp
